-- AlterTable
ALTER TABLE "media" ALTER COLUMN "assest_id" DROP NOT NULL,
ALTER COLUMN "public_id" DROP NOT NULL,
ALTER COLUMN "formet" DROP NOT NULL,
ALTER COLUMN "url" DROP NOT NULL,
ALTER COLUMN "folder" DROP NOT NULL,
ALTER COLUMN "api_key" DROP NOT NULL,
ALTER COLUMN "original_filename" DROP NOT NULL;
